# Generated by Django 4.2.6 on 2024-09-04 21:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id_atencion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('motivo_atencion', models.CharField(max_length=1000)),
                ('fecha_atencion', models.DateField(default=datetime.date.today)),
                ('observacion_atencion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id_especialidad', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_especialidad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hora_reserva', models.DateTimeField(default=datetime.datetime.now, help_text='Fecha y hora de la reserva.')),
                ('fecha_reserva', models.DateField(default=datetime.date.today, help_text='Fecha en la que se hizo la reserva.')),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tipo_usuario', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id_tratamiento', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_tratamiento', models.CharField(max_length=100)),
                ('costo_tratamiento', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_usuario', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_usu', models.CharField(max_length=100)),
                ('direccion_usu', models.CharField(max_length=200)),
                ('correo_usu', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('ciudad', models.CharField(max_length=50)),
                ('comuna', models.CharField(max_length=50)),
                ('rut_usu', models.CharField(max_length=12, unique=True)),
                ('correo_vet', models.EmailField(blank=True, max_length=254, null=True)),
                ('tipo_permiso', models.CharField(max_length=50)),
                ('icono', models.ImageField(blank=True, null=True, upload_to='user_icons/')),
                ('status', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.group')),
                ('id_especialidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.especialidad')),
                ('id_tipo_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tipousuario')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_permissions_set', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mascota', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_mascota', models.CharField(max_length=100)),
                ('edad_mascota', models.IntegerField(blank=True, null=True)),
                ('especie_mascota', models.CharField(max_length=100)),
                ('raza_mascota', models.CharField(max_length=100)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id_ficha', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sintomas', models.CharField(max_length=1000)),
                ('examenes', models.CharField(max_length=200)),
                ('observacion_ficha', models.CharField(max_length=200)),
                ('id_atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atencion', to='app.atencion')),
                ('id_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascota', to='app.mascota')),
                ('id_tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamiento', to='app.tratamiento')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='app.usuario')),
            ],
        ),
    ]
